### ISSUE TITLE
exa completion not working

### ISSUE THREAD

**Issue by crazy-matt** [Seirdy/dotfiles#1]
Hi Seirdy,
I don't know if it's the right place to get in touch with you. I liked your zinit config and took some inspiration from it.
About exa, it wasn't working. I figured out that the snippet link needed to be updated from the current one (https://github.com/ogham/exa/blob/master/contrib/completions.zsh) in your config to the new one (https://github.com/ogham/exa/blob/master/completions/completions.zsh).

However I'm still not able to make it work.
Here is the last thing I tried:
```
zinit ice lucid wait'0a' as'completion' blockf \
  mv'completions.zsh -> _exa'
zinit snippet https://github.com/ogham/exa/blob/master/completions/completions.zsh
```

I started with zinit few weeks ago so I wouldn't refuse any advice.

Cheers

**Comment by Seirdy** [comment]
On Thu, Feb 25, 2021 at 11:12:12AM -0800, crazy-matt wrote:
>Here is the last thing I tried:
>```
>zinit ice lucid wait'0a' as'completion' blockf \
>  mv'completions.zsh -> _exa'
>zinit snippet https://github.com/ogham/exa/blob/master/completions/completions.zsh
>```

Thanks, fixed.

-- 
/Seirdy

**Comment by crazy-matt** [comment]
I'm surprised it worked for you. Do you see the `completions/_exa` file?
I can't make it work even if the snippet get downloaded well.

**Comment by Seirdy** [comment]
On Fri, Feb 26, 2021 at 08:32:29AM -0800, crazy-matt wrote:
>I'm surprised it worked for you. Do you see the `completions/_exa` file?
>I can't make it work even if the snippet get downloaded well.

Seems to be in the right place for me.

-- 
/Seirdy
